-- first day : List all films and their categories.

SELECT
	FILM.TITLE,
	CATEGORY.NAME,
	FILM.DESCRIPTION
FROM
	FILM
	INNER JOIN FILM_CATEGORY ON FILM_CATEGORY.FILM_ID = FILM.FILM_ID
	INNER JOIN CATEGORY ON FILM_CATEGORY.CATEGORY_ID = CATEGORY.CATEGORY_ID;

-- Find all films that do not have any actors.
SELECT
    FILM.FILM_ID,
    FILM.TITLE
FROM
    FILM
    LEFT JOIN FILM_ACTOR ON FILM.FILM_ID = FILM_ACTOR.FILM_ID
WHERE
    FILM_ACTOR.FILM_ID IS NULL;